# Turkish translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# audi06_19 <info@dreamosat-forum.com>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: enigma2-vision-core\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-03-21 01:09+0300\n"
"PO-Revision-Date: 2020-03-21 01:13+0300\n"
"Last-Translator: audi06_19 <info@dreamosat-forum.com>\n"
"Language-Team: Turkish\n"
"Language: tr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Poedit 2.2.1\n"
"X-Poedit-SourceCharset: UTF-8\n"

#: BackupManager.py:49 ImageManager.py:46
msgid "30 Days"
msgstr "30 Gün"

#: BackupManager.py:49 ImageManager.py:46
msgid "Daily"
msgstr "Günlük"

#: BackupManager.py:49 ImageManager.py:46
msgid "Weekly"
msgstr "Haftalık"

#: BackupManager.py:131 BackupManager.py:181 BackupManager.py:313
#: BackupManager.py:328 BackupManager.py:371 BackupManager.py:389
#: BackupManager.py:1103 ImageManager.py:350 ui.py:49
msgid "Backup manager"
msgstr "Yedekleme yöneticisi"

#: BackupManager.py:139
msgid "Restore"
msgstr "Geri yükle"

#: BackupManager.py:140 ImageManager.py:115 SwapManager.py:188
msgid "Delete"
msgstr "Sil"

#: BackupManager.py:155 BackupManager.py:289 ImageManager.py:135
#: ImageManager.py:291
msgid "%a %e %b  %-H:%M"
msgstr "%a %e %b  %-H:%M"

#: BackupManager.py:155 BackupManager.py:157 BackupManager.py:289
#: BackupManager.py:291 ImageManager.py:135 ImageManager.py:137
#: ImageManager.py:291 ImageManager.py:293
msgid "Next backup: "
msgstr "Sonraki yedekleme: "

#: BackupManager.py:184 BackupManager.py:325 BackupManager.py:368
#: ImageManager.py:164 ImageManager.py:337
msgid "View progress"
msgstr "İlerlemeyi görüntüle"

#: BackupManager.py:186 ImageManager.py:166
msgid "New backup"
msgstr "Yeni yedekleme"

#: BackupManager.py:213
msgid "Device: none available"
msgstr "Cihaz: mevcut değil"

#: BackupManager.py:213 ImageManager.py:216
msgid "Press 'Menu' to select a storage device"
msgstr "Bir depolama cihazı seçmek için 'Menü'ye basın"

#: BackupManager.py:229 BackupManager.py:232
msgid "Select a backup to restore:"
msgstr "Geri yüklenecek bir yedek seçin:"

#: BackupManager.py:229 ImageManager.py:235
msgid "The chosen location does not exist, using /media/hdd."
msgstr "/media/hdd kullanılarak seçilen konum mevcut değil."

#: BackupManager.py:232 BackupManager.py:252 ImageManager.py:240
#: ImageManager.py:249 MountManager.py:138 MountManager.py:257
#: MountManager.py:272
msgid "Device: "
msgstr "Cihaz: "

#: BackupManager.py:252 ImageManager.py:249
msgid "There is a problem with this device. Please reformat it and try again."
msgstr "Bu cihazla ilgili bir sorun var. Lütfen yeniden biçimlendirin ve tekrar deneyin."

#: BackupManager.py:297
msgid ""
"Are you sure you want to delete this backup:\n"
" "
msgstr ""
"Bu yedeklemeyi silmek istediğinizden emin misiniz:\n"
" "

#: BackupManager.py:299 ImageManager.py:301 Multibootmgr.py:119
#: Multibootmgr.py:123 Multibootmgr.py:138
msgid "Remove confirmation"
msgstr "Onayı kaldır"

#: BackupManager.py:301
msgid "There is no backup to delete."
msgstr "Silinecek yedek yok."

#: BackupManager.py:342
msgid "There is no backup to restore."
msgstr "Geri yüklenecek yedek yok."

#: BackupManager.py:344
msgid ""
"Backup in progress,\n"
"Please wait for it to finish, before trying again."
msgstr ""
"Yedekleme devam ediyor,\n"
"Lütfen tekrar denemeden önce bitmesini bekleyin."

#: BackupManager.py:355 BackupManager.py:357 RestoreWizard.py:182
#: RestoreWizard.py:186
msgid "Sorry, but the file is not compatible with this image version."
msgstr "Maalesef dosya bu resim sürümüyle uyumlu değil."

#: BackupManager.py:360
msgid ""
"Are you sure you want to restore this backup:\n"
" "
msgstr ""
"Bu yedeklemeyi geri yüklemek istediğinizden emin misiniz:\n"
" "

#: BackupManager.py:362
msgid "Restore Confirmation"
msgstr "Onayı Geri Yükle"

#: BackupManager.py:391 BackupManager.py:395 BackupManager.py:399
msgid "Restoring backup..."
msgstr "Yedekleme geri yükleniyor ..."

#: BackupManager.py:403 BackupManager.py:407 BackupManager.py:1113
#: BackupManager.py:1117
msgid "Creating list of installed plugins..."
msgstr "Yüklü eklentiler listesi yaratılıyor ..."

#: BackupManager.py:411 BackupManager.py:415
msgid "Comparing against backup..."
msgstr "Yedekle karşılaştırılıyor ..."

#: BackupManager.py:419 BackupManager.py:423
msgid "Restoring plugins..."
msgstr "Eklentiler geri yükleniyor ..."

#: BackupManager.py:427 BackupManager.py:431
msgid "Restoring plugins, this can take a long time..."
msgstr "Eklentileri geri yüklemek uzun zaman alabilir ..."

#: BackupManager.py:435
msgid "Rebooting..."
msgstr "Yeniden başlatılıyor ..."

#: BackupManager.py:443
msgid "Do you want to restore your enigma2 settings ?"
msgstr "Enigma2 ayarlarınızı geri yüklemek istiyor musunuz?"

#: BackupManager.py:474
msgid "Sorry, but the restore failed."
msgstr "Üzgünüm, ancak geri yükleme başarısız."

#: BackupManager.py:501 RestoreWizard.py:156 RestoreWizard.py:267
msgid "A background update check is in progress, please try again."
msgstr "Bir arka plan güncelleme kontrolü devam ediyor, lütfen tekrar deneyin."

#: BackupManager.py:538
msgid "Your STB is not connected to a network. Please check your network settings and try again."
msgstr "STB'niz bir ağa bağlı değil. Lütfen ağ ayarlarınızı kontrol edin ve tekrar deneyin."

#: BackupManager.py:547
msgid "Sorry the feeds are down for maintenance. Please try again later."
msgstr "Üzgünüz, özet akışları bakım için kapalı. Lütfen daha sonra tekrar deneyin."

#: BackupManager.py:556
msgid "Your STB is not connected to the Internet. Please check your network settings and try again."
msgstr "STB'niz İnternet'e bağlı değil. Lütfen ağ ayarlarınızı kontrol edin ve tekrar deneyin."

#: BackupManager.py:648
msgid "Do you want to restore your Enigma2 plugins ?"
msgstr "Enigma2 eklentilerinizi geri yüklemek istiyor musunuz?"

#: BackupManager.py:665
msgid "Now skipping restore process"
msgstr "Şimdi geri yükleme işlemi atlanıyor"

#: BackupManager.py:714
msgid "Select files/folders to backup"
msgstr "Yedeklenecek dosyaları / klasörleri seç"

#: BackupManager.py:718 BackupManager.py:809 BackupManager.py:908
#: MountManager.py:336 Multibootmgr.py:43 Multibootmgr.py:65
msgid "Cancel"
msgstr "İptal"

#: BackupManager.py:719 BackupManager.py:810 MountManager.py:335
msgid "Save"
msgstr "Kaydet"

#: BackupManager.py:752
msgid "Deselect"
msgstr "Seçimi kaldır"

#: BackupManager.py:754
msgid "Select"
msgstr "Seç"

#: BackupManager.py:805
msgid "Select extra packages folder"
msgstr "Ek paketler klasörü seç"

#: BackupManager.py:839
msgid "Select folder that contains plugins"
msgstr "Eklentiler içeren klasörü seç"

#: BackupManager.py:865
msgid "Please enter a folder that contains some packages."
msgstr "Lütfen bazı paketler içeren bir klasör girin."

#: BackupManager.py:909 RestoreWizard.py:108
msgid "OK"
msgstr "Tamam"

#: BackupManager.py:910
msgid "Choose files"
msgstr "Dosya seç"

#: BackupManager.py:911
msgid "Choose local IPK's folder"
msgstr "Yerel IPK'nın klasörünü seç"

#: BackupManager.py:934 SoftcamManager.py:522
msgid "Logs"
msgstr "Günlükler"

#: BackupManager.py:940
msgid "Backup created"
msgstr "Yedek oluşturuldu"

#: BackupManager.py:1042
msgid ""
"Your STB is about to run a backup of your settings and to detect your plugins.\n"
"Do you want to allow this?"
msgstr ""
"STB'niz ayarlarınızın bir yedeğini çalıştırmak ve eklentilerinizi tespit etmek üzere.\n"
"Buna izin vermek ister misin?"

#: BackupManager.py:1067 ImageManager.py:629
msgid "Enough retries, delaying till next schedule."
msgstr "Bir sonraki programa kadar erteleme yeterlidir."

#: BackupManager.py:1105 BackupManager.py:1109
msgid "Starting..."
msgstr "Başlatılıyor ..."

#: BackupManager.py:1121 BackupManager.py:1125 BackupManager.py:1137
#: BackupManager.py:1141
msgid "Backing up files..."
msgstr "Dosyalar yedekleniyor ..."

#: BackupManager.py:1129 BackupManager.py:1133
msgid "Preparing extra plugins..."
msgstr "Fazladan eklentiler hazırlanıyor ..."

#: BackupManager.py:1145
msgid "Backup complete..."
msgstr "Yedekleme tamamlandı ..."

#: BackupManager.py:1206
msgid "The backup location does not have enough free space."
msgstr "Yedekleme yerinde yeterli boş alan yok."

#: BackupManager.py:1246
msgid "Plugin listing failed - e. g. wrong backup destination or no space left on backup device."
msgstr "Eklenti listesi başarısız oldu - örneğin yanlış yedekleme hedefi veya yedekleme cihazında boş alan kalmadı."

#: BackupManager.py:1311
msgid "Backup failed - e. g. wrong backup destination or no space left on backup device."
msgstr "Yedekleme başarısız - örn. yanlış yedekleme hedefi veya yedekleme cihazında boş alan kalmamış."

#: H9SDmanager.py:30
msgid "H9 SDcard manager"
msgstr "H9 SD kart yöneticisi"

#: H9SDmanager.py:36
msgid "Press appropiate Init to move Nand root to SDcard."
msgstr "Nand ​​kökü SDcard'a taşımak için uygun Init tuşuna basın."

#: H9SDmanager.py:37
msgid "Reboot"
msgstr "Yeniden başlat"

#: H9SDmanager.py:38 Multibootmgr.py:46 Multibootmgr.py:70
msgid "Init SDcard"
msgstr "SDcard'ı başlat"

#: H9SDmanager.py:53
msgid "Init Zgemma H9 SDCARD - please reboot after use."
msgstr "Init Zgemma H9 SDCARD - lütfen kullanımdan sonra yeniden başlatın."

#: H9SDmanager.py:77
msgid "Init Zgemma H9 USB/SDA1 - please reboot after use."
msgstr "Init Zgemma H9 USB / SDA1 - lütfen kullanımdan sonra yeniden başlatın."

#: IPKInstaller.py:35 IPKInstaller.py:167
msgid "IPK installer"
msgstr "IPK yükleyici"

#: IPKInstaller.py:52 IPKInstaller.py:174 ImageManager.py:1327
#: SoftcamManager.py:102 SwapManager.py:114 ui.py:60
msgid "Close"
msgstr "Kapat"

#: IPKInstaller.py:53 IPKInstaller.py:175
msgid "Install"
msgstr "Yükle"

#: IPKInstaller.py:81 IPKInstaller.py:100
msgid "Extra IPK's"
msgstr "Ekstra IPK'lar"

#: IPKInstaller.py:84
msgid "It seems you have not setup an extra location. Please set it up in the Backup manager setup menu."
msgstr "Görünüşe göre fazladan bir konum ayarlamadınız. Lütfen bunu Backup manager kurulum menüsünde ayarlayın."

#: IPKInstaller.py:86 IPKInstaller.py:90
msgid "Change location"
msgstr "Konumu değiştir"

#: IPKInstaller.py:88
msgid "Sorry but that location does not exist or is not setup. Please set it up in the Backup manager setup menu."
msgstr "Maalesef bu konum mevcut değil veya ayarlanmadı. Lütfen bunu Backup manager ayarlar menüsünde ayarlayın."

#: IPKInstaller.py:94 IPKInstaller.py:102
msgid "Temp folder"
msgstr "Temp klasörü"

#: IPKInstaller.py:104
msgid "Select a package to install:"
msgstr "Kurulacak paketi seçin:"

#: IPKInstaller.py:122
msgid "Are you ready to install ?"
msgstr "Yüklemeye hazır mısınız?"

#: IPKInstaller.py:124
msgid "Install confirmation"
msgstr "Yükleme onayı"

#: IPKInstaller.py:132
msgid "Installing..."
msgstr "Yükleniyor ..."

#: IPKInstaller.py:135
msgid "Do you want to restart GUI now ?"
msgstr "GUI'yi şimdi yeniden başlatmak istiyor musunuz?"

#: IPKInstaller.py:137
msgid "Restart GUI."
msgstr "GUI'yi yeniden başlat."

#: IPKInstaller.py:177
msgid "Invert"
msgstr "Tersine çevir"

#: IPKInstaller.py:178
msgid "Press OK to toggle the selection."
msgstr "Seçimi değiştirmek için OK tuşuna basın."

#: ImageManager.py:105 ImageManager.py:161 ImageManager.py:319
#: ImageManager.py:340 ImageManager.py:742 ui.py:50
msgid "Image manager"
msgstr "Görüntü yöneticisi"

#: ImageManager.py:112
msgid "Flash"
msgstr "Flash"

#: ImageManager.py:114 ImageManager.py:1320
msgid "Downloads"
msgstr "İndirilenler"

#: ImageManager.py:216
msgid "Device: None available"
msgstr "Cihaz: Yok"

#: ImageManager.py:235 ImageManager.py:240
msgid "Select an image to flash:"
msgstr "Flaşlanacak bir resim seçin:"

#: ImageManager.py:240
msgid "Free space:"
msgstr "Boş alan:"

#: ImageManager.py:240 MountManager.py:127
msgid "MB"
msgstr "MB"

#: ImageManager.py:257
msgid "Do you want to change download url"
msgstr "İndirme URL'sini değiştirmek istiyor musunuz"

#: ImageManager.py:265
msgid "'User' url has not been specified, please use MENU button to initialise"
msgstr "'Kullanıcı' URL'si belirtilmedi, lütfen başlatmak için MENU düğmesini kullanın"

#: ImageManager.py:299
msgid ""
"Are you sure you want to delete this image backup:\n"
" "
msgstr ""
"Bu resim yedeklemesini silmek istediğinizden emin misiniz:\n"
" "

#: ImageManager.py:303
msgid "There is no image to delete."
msgstr "Silinecek resim yok."

#: ImageManager.py:328
msgid ""
"Do you want to create a full image backup?\n"
"This can take about 6 minutes to complete."
msgstr ""
"Tam bir görüntü yedeği oluşturmak istiyor musunuz?\n"
"Bu işlemin tamamlanması yaklaşık 6 dakika sürebilir."

#: ImageManager.py:330
msgid "Backup confirmation"
msgstr "Yedekleme onayı"

#: ImageManager.py:368
#, python-format
msgid ""
"Recording(s) are in progress or coming up in few seconds!\n"
"Do you still want to flash image\n"
"%s?"
msgstr ""
"Kayıtlar devam ediyor veya birkaç saniye içinde çıkıyor!\n"
"Hala görüntüyü flaş etmek istiyor musunuz\n"
"%s?"

#: ImageManager.py:370
#, python-format
msgid ""
"Do you want to flash image\n"
"%s"
msgstr ""
"Görüntüyü flaş etmek istiyor musunuz\n"
"%s"

#: ImageManager.py:372
msgid ""
"You are about to flash an eMMC flash; we cannot take any responsibility for any errors or damage to your box during this process.\n"
"Proceed with CAUTION!:\n"
"Are you sure you want to flash this image:\n"
" "
msgstr ""
"Bir eMMC flaşı yanıp sönmek üzeresiniz; bu işlem sırasında kutunuzdaki herhangi bir hata veya hasar için herhangi bir sorumluluk kabul edemeyiz.\n"
"DİKKAT ile devam edin!:\n"
"Bu resmi flaşlamak istediğinizden emin misiniz:\n"
" "

#: ImageManager.py:374
msgid ""
"Are you sure you want to flash this image:\n"
" "
msgstr ""
"Bu resmi flaşlamak istediğinizden emin misiniz:\n"
" "

#: ImageManager.py:376
msgid "Flash confirmation"
msgstr "Flaş onayı"

#: ImageManager.py:405
#, python-format
msgid "slot%s - %s"
msgstr "slot%s - %s"

#: ImageManager.py:405
#, python-format
msgid "slot%s - %s (current image)"
msgstr "slot%s - %s (geçerli resim)"

#: ImageManager.py:421
msgid "There is no image to flash."
msgstr "Flash görüntü yok."

#: ImageManager.py:423
msgid "You have decided not to flash image."
msgstr "Görüntüyü flaş etmemeye karar verdiniz."

#: ImageManager.py:428
msgid "Please wait while the flash prepares, after the image is flashed, your STB will restart - if error please use Recovery mode to restart."
msgstr "Lütfen flaş hazırlanırken bekleyin, görüntü yanıp söndükten sonra STB'niz yeniden başlar - hata oluşursa lütfen yeniden başlatmak için Kurtarma modunu kullanın."

#: ImageManager.py:430
msgid "Please wait while the flash prepares."
msgstr "Lütfen flaş hazırlanırken bekleyin."

#: ImageManager.py:442
msgid "Flash image unzip successful."
msgstr "Flash resmi unzip başarılı."

#: ImageManager.py:444
msgid ""
"ET8500 Multiboot: Yes to restore OS1 No to restore OS2:\n"
" "
msgstr ""
"ET8500 Multiboot: OS1'i geri yüklemek için Evet OS2'yi geri yüklemek için Hayır:\n"
" "

#: ImageManager.py:446
msgid "ET8500 Image Restore"
msgstr "ET8500 Görüntü Geri Yükleme"

#: ImageManager.py:450 ImageManager.py:1223
msgid "Multiboot only able to restore this backup to mmc slot1"
msgstr "Çoklu önyükleme yalnızca bu yedeklemeyi mmc slot1'e geri yükleyebilir"

#: ImageManager.py:456
#, python-format
msgid ""
"Unzip error (also sent to any debug log):\n"
"%s"
msgstr ""
"Sıkıştırılmış hata (hata ayıklama günlüğüne de gönderilir):\n"
"%s"

#: ImageManager.py:503
#, python-format
msgid ""
"OFGwrite error (also sent to any debug log):\n"
"%s"
msgstr ""
"OFGwrite hatası (hata ayıklama günlüğüne de gönderilir):\n"
"%s"

#: ImageManager.py:512
msgid "Multiboot ERROR! - no STARTUP in boot partition."
msgstr "Çoklu önyükleme HATASI! - önyükleme bölümünde BAŞLATMA yok."

#: ImageManager.py:604
msgid ""
"Your STB is about to create a full image backup, this can take about 6 minutes to complete.\n"
"Do you want to allow this?"
msgstr ""
"STB'niz tam bir görüntü yedeği oluşturmak üzere, bu işlemin tamamlanması yaklaşık 6 dakika sürebilir.\n"
"Buna izin vermek ister misin?"

#: ImageManager.py:744
msgid "Setting up..."
msgstr "Ayarlanıyor ..."

#: ImageManager.py:748
msgid "Checking free RAM.."
msgstr "Ücretsiz RAM denetleniyor .."

#: ImageManager.py:752
msgid "Creating SWAP.."
msgstr "SWAP oluşturuluyor .."

#: ImageManager.py:756 ImageManager.py:760
msgid "Backing up kernel..."
msgstr "Çekirdek yedekleniyor ..."

#: ImageManager.py:764 ImageManager.py:768
msgid "Backing up root file system..."
msgstr "Kök dosya sistemi yedekleniyor ..."

#: ImageManager.py:772
msgid "Backing up eMMC partitions for USB flash ..."
msgstr "USB flash için eMMC bölümleri yedekleniyor ..."

#: ImageManager.py:776
msgid "Backing up eMMC partitions for USB flash..."
msgstr "USB flash için eMMC bölümleri yedekleniyor ..."

#: ImageManager.py:780 ImageManager.py:784
msgid "Removing temp mounts..."
msgstr "Geçici bağlantıların kaldırılması ..."

#: ImageManager.py:788 ImageManager.py:792
msgid "Moving to backup Location..."
msgstr "Yedeği yedeklemeye geçiliyor ..."

#: ImageManager.py:796 ImageManager.py:800
msgid "Creating zip..."
msgstr "Zip oluşturuluyor ..."

#: ImageManager.py:804
msgid "Backup complete."
msgstr "Yedekleme tamamlandı."

#: ImageManager.py:825
msgid "The backup location does not have enough free space.\n"
msgstr "Yedekleme yerinde yeterli boş alan yok.\n"

#: ImageManager.py:862
msgid "Sorry, not enough free RAM found, and no physical devices that supports SWAP attached. Can't create SWAP file on network or fat32 file-systems, unable to make backup."
msgstr "Üzgünüm, yeterli boş RAM bulunamadı ve SWAP'ı destekleyen fiziksel cihazlar bağlı değil. Ağda veya fat32 dosya sistemlerinde SWAP dosyası oluşturulamıyor, yedekleme yapılamıyor."

#: ImageManager.py:950 ImageManager.py:953 ImageManager.py:956
#: ImageManager.py:958 ImageManager.py:960
msgid "Create:"
msgstr "Oluştur:"

#: ImageManager.py:1326
msgid "Select an image to download for STB:"
msgstr "STB için indirmek için bir resim seçin:"

#: ImageManager.py:1328
msgid "Download"
msgstr "İndir"

#: ImageManager.py:1335
msgid "No images found for selected download server...if password check validity"
msgstr "Seçilen indirme sunucusu için resim bulunamadı ... eğer şifre kontrol geçerliliği"

#: ImageManager.py:1375
#, python-format
msgid "Image Version %s"
msgstr "Görüntü Sürümü%s"

#: ImageManager.py:1445
msgid "Compress"
msgstr "Sıkıştır"

#: ImageManager.py:1445
msgid "Expand"
msgstr "Genişlet"

#: ImageManager.py:1447
msgid "DownLoad"
msgstr "DownLoad"

#: ImageManager.py:1477
msgid ""
"Are you sure you want to download this image:\n"
" "
msgstr ""
"Bu resmi indirmek istediğinizden emin misiniz:\n"
" "

#: ImageManager.py:1479
msgid "Download confirmation"
msgstr "İndirme onayı"

#: ImageManager.py:1496
msgid "Downloading"
msgstr "İndiriliyor"

#: MountManager.py:78
msgid "HARD DISK: "
msgstr "SABİT DİSK: "

#: MountManager.py:90
msgid "USB: "
msgstr "USB: "

#: MountManager.py:96
msgid "SDCARD: "
msgstr "SDCARD: "

#: MountManager.py:103 MountManager.py:105 MountManager.py:116
msgid "None"
msgstr "Yok"

#: MountManager.py:104 MountManager.py:117 MountManager.py:129
msgid "unavailable"
msgstr "kullanılamıyor"

#: MountManager.py:117 MountManager.py:123 MountManager.py:125
#: MountManager.py:127 MountManager.py:129
msgid "Size: "
msgstr "Boyut: "

#: MountManager.py:123
msgid "TB"
msgstr "TB"

#: MountManager.py:125
msgid "GB"
msgstr "GB"

#: MountManager.py:138 MountManager.py:256 MountManager.py:271
msgid "Mount: "
msgstr "Bağla: "

#: MountManager.py:138
msgid "Type: "
msgstr "Tür: "

#: MountManager.py:189 ui.py:52
msgid "Mount manager"
msgstr "Mount yöneticisi"

#: MountManager.py:195
msgid "Setup mounts"
msgstr "Kurulum bağlar"

#: MountManager.py:196
msgid "Un-mount"
msgstr "Montajdan kaldır"

#: MountManager.py:197
msgid "Mount"
msgstr "Bağla"

#: MountManager.py:219
msgid "Use as HDD"
msgstr "HDD Olarak Kullan"

#: MountManager.py:235
msgid "Please wait while scanning for devices..."
msgstr "Lütfen cihazları tararken bekleyin ..."

#: MountManager.py:262
msgid "Mount failed."
msgstr "Bağlama başarısız."

#: MountManager.py:279
msgid "Can't un-mount the partition; make sure it is not being used for SWAP or record/timeshift paths."
msgstr "Bölüm kaldırılamıyor; SWAP veya kayıt / zaman kaydırma yolları için kullanılmadığından emin olun."

#: MountManager.py:296
msgid "This device is already mounted as HDD."
msgstr "Bu aygıt zaten HDD olarak monte edilmiş."

#: MountManager.py:331
msgid "Choose where to mount your devices to:"
msgstr "Cihazlarınızı nereye monte edeceğinizi seçin:"

#: MountManager.py:345
msgid "Please wait while scanning your STB devices..."
msgstr "Lütfen STB cihazlarınızı tararken bekleyin ..."

#: MountManager.py:367
msgid "Updating mount locations..."
msgstr "Bağlama konumları güncelleniyor ..."

#: MountManager.py:369
msgid "Please wait."
msgstr "Lütfen bekleyin."

#: MountManager.py:372
msgid ""
"The changes need a system restart to take effect.\n"
"Restart your STB now?"
msgstr ""
"Değişikliklerin etkili olması için sistemin yeniden başlatılması gerekiyor.\n"
"STB'nizi şimdi yeniden başlatmak istiyor musunuz?"

#: MountManager.py:374
msgid "Restart STB."
msgstr "STB'yi yeniden başlat."

#: Multibootmgr.py:36
msgid "Multiboot image manager"
msgstr "Çoklu önyükleme görüntü yöneticisi"

#: Multibootmgr.py:44
msgid "Press Init to format SDcard."
msgstr "SD kartı formatlamak için Init tuşuna basın."

#: Multibootmgr.py:66
msgid "Use the cursor keys to select an installed image and then Erase button."
msgstr "Yüklü bir görüntüyü seçmek için imleç tuşlarını kullanın ve ardından Sil düğmesini tıklayın."

#: Multibootmgr.py:67
msgid "Note: slot list does not show current image or empty slots."
msgstr "Not: yuva listesi geçerli görüntüyü veya boş yuvaları göstermiyor."

#: Multibootmgr.py:68
msgid "Erase"
msgstr "Sil"

#: Multibootmgr.py:73
msgid "Retrieving image slots - Please wait..."
msgstr "Görüntü yuvaları alınıyor - Lütfen bekleyin ..."

#: Multibootmgr.py:108
msgid "Empty slot"
msgstr "Boş yuva"

#: Multibootmgr.py:109
#, python-format
msgid "slot%s - %s "
msgstr "slot%s - %s "

#: Multibootmgr.py:117
#, python-format
msgid "Removal of this slot will not show in STB GUI.  Are you sure you want to delete image slot %s ?"
msgstr "Bu yuvanın kaldırılması STB GUI'de gösterilmeyecek.%s resim yuvasını silmek istediğinizden emin misiniz?"

#: Multibootmgr.py:121
#, python-format
msgid "Are you sure you want to delete image slot %s ?"
msgstr "% s resim yuvasını silmek istediğinizden emin misiniz?"

#: Multibootmgr.py:131
msgid "Init SDCARD"
msgstr "SDCARD'ı başlat"

#: Multibootmgr.py:133
msgid "Multiboot manager - Cannot initialise SDcard when running image on SDcard."
msgstr "Çoklu önyükleme yöneticisi - Görüntüyü SDcard üzerinde çalıştırırken SDcard başlatılamıyor."

#: Multibootmgr.py:136
msgid "Multiboot manager - to use this routine STB image must be at OpenVision 4.2.043 or later and USB flashed - reply Yes to continue"
msgstr "Çoklu önyükleme yöneticisi - bu rutin STB görüntüsünü kullanmak için OpenVision 4.2.043 veya sonrasında olmalı ve USB yanıp sönüyor - devam etmek için Evet yanıtını verin"

#: Multibootmgr.py:146
msgid "Multiboot manager - The SDcard must be at least 8MB."
msgstr "Çoklu önyükleme yöneticisi - SD kart en az 8 MB olmalıdır."

#: Multibootmgr.py:161
msgid "Multiboot manager - SDcard initialization run, please restart your Image."
msgstr "Çoklu önyükleme yöneticisi - SDcard başlatma çalıştırması, lütfen Resminizi yeniden başlatın."

#: RestoreWizard.py:90
msgid "Exit the restore wizard"
msgstr "Geri yükleme sihirbazından çık"

#: RestoreWizard.py:90
msgid "OK, to perform a restore"
msgstr "Tamam, geri yükleme gerçekleştirmek için"

#: RestoreWizard.py:94
msgid "NO, do not restore settings"
msgstr "HAYIR, ayarları geri yükleme"

#: RestoreWizard.py:94
msgid "YES, to restore settings"
msgstr "EVET, ayarları geri yüklemek için"

#: RestoreWizard.py:100 RestoreWizard.py:103
msgid "YES, to restore plugins"
msgstr "EVET, eklentileri geri yüklemek için"

#: RestoreWizard.py:101 RestoreWizard.py:104
msgid "NO, do not restore plugins"
msgstr "HAYIR, eklentileri geri yükleme"

#: RestoreWizard.py:128 RestoreWizard.py:133
msgid "Please wait while the system gathers information..."
msgstr "Lütfen sistem bilgi toplarken bekleyin ..."

#: RestoreWizard.py:129 RestoreWizard.py:134 RestoreWizard.py:141
#: RestoreWizard.py:147 RestoreWizard.py:153 RestoreWizard.py:157
#: RestoreWizard.py:183 RestoreWizard.py:187 RestoreWizard.py:196
#: RestoreWizard.py:252 RestoreWizard.py:256 RestoreWizard.py:260
#: RestoreWizard.py:264 RestoreWizard.py:268 plugin.py:178
msgid "Restore wizard"
msgstr "Geri yükleme sihirbazı"

#: RestoreWizard.py:140
msgid "Please wait while plugins restore completes..."
msgstr "Lütfen eklentilerin geri yüklenmesi tamamlanırken bekleyin ..."

#: RestoreWizard.py:146
msgid "Sorry the feeds are down for maintenance. Please try using Backup manager to restore plugins later."
msgstr "Üzgünüz, özet akışları bakım için kapalı. Lütfen eklentileri daha sonra geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:152
msgid "Your STB is not connected to the Internet. Please try using Backup manager to restore plugins later."
msgstr "STB'niz İnternet'e bağlı değil. Lütfen eklentileri daha sonra geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:195
msgid "Please wait while settings restore completes..."
msgstr "Lütfen ayarların geri yüklenmesi tamamlanırken bekleyin ..."

#: RestoreWizard.py:251
msgid "Your STB is not connected to a network. Please try using the Backup manager to restore plugins later when a network connection is available."
msgstr "STB'niz bir ağa bağlı değil. Lütfen daha sonra bir ağ bağlantısı olduğunda eklentileri geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:255
msgid "Your STB could not connect to the plugin feeds at this time. Please try using the Backup manager to restore plugins later."
msgstr "STB'niz şu anda eklenti özet akışlarına bağlanamadı. Lütfen eklentileri daha sonra geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:259
msgid "Your STB is not connected to the Internet. Please try using the Backup manager to restore plugins later."
msgstr "STB'niz İnternet'e bağlı değil. Lütfen eklentileri daha sonra geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:263
msgid "Sorry the feeds are down for maintenance. Please try using the Backup manager to restore plugins later."
msgstr "Üzgünüz, özet akışları bakım için kapalı. Lütfen eklentileri daha sonra geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: ScriptRunner.py:41 plugin.py:172 ui.py:53
msgid "Script runner"
msgstr "Komut dosyası koşucusu"

#: ScriptRunner.py:47
msgid "Run"
msgstr "Çalıştır"

#: SoftcamManager.py:74 plugin.py:96 plugin.py:170
msgid "Softcam manager"
msgstr "Softcam yöneticisi"

#: SoftcamManager.py:75 ui.py:43
msgid "Main menu"
msgstr "Ana menü"

#: SoftcamManager.py:75 ui.py:43
msgid "Setup"
msgstr "Kurulum"

#: SoftcamManager.py:75
msgid "Softcam"
msgstr "Softcam"

#: SoftcamManager.py:79
msgid "Select:"
msgstr "Seç:"

#: SoftcamManager.py:80 SoftcamManager.py:146
msgid "Active:"
msgstr "Aktif:"

#: SoftcamManager.py:105 SwapManager.py:117
msgid "Autostart"
msgstr "Otomatik başlatma"

#: SoftcamManager.py:133
msgid "Start"
msgstr "Başlat"

#: SoftcamManager.py:135
msgid "Stop"
msgstr "Durdur"

#: SoftcamManager.py:139
msgid "Restart"
msgstr "Yeniden başlat"

#: SoftcamManager.py:142
msgid "Disable startup"
msgstr "Başlamayı devre dışı bırak"

#: SoftcamManager.py:144
msgid "Enable startup"
msgstr "Başlatmayı etkinleştir"

#: SoftcamManager.py:165
msgid ""
"Wait please while scanning\n"
"for softcam's..."
msgstr ""
"Tarama sırasında lütfen bekleyin\n"
"softcam için ..."

#: SoftcamManager.py:210 SoftcamManager.py:274
msgid ""
"No config files found, please setup CCcam first\n"
"in /etc/CCcam.cfg."
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce CCcam kurulumunu yapın\n"
"/etc/CCcam.cfg içinde."

#: SoftcamManager.py:215
msgid "CCcam can't run whilst MGcamd is running"
msgstr "MGcamd çalışırken CCcam çalışamıyor"

#: SoftcamManager.py:218
msgid ""
"No config files found, please setup Hypercam first\n"
"in /etc/hypercam.cfg."
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce Hypercam'ı kurun\n"
"/etc/hypercam.cfg içinde."

#: SoftcamManager.py:223
msgid ""
"No config files found, please setup Oscam first\n"
"in /etc/tuxbox/config"
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce Oscam'i kurun\n"
"/etc/tuxbox/config içinde"

#: SoftcamManager.py:229 SoftcamManager.py:285
msgid ""
"No config files found, please setup MGcamd first\n"
"in /usr/keys."
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce MGcamd kurulumunu yapın\n"
"içinde /usr/keys."

#: SoftcamManager.py:231 SoftcamManager.py:287
msgid "MGcamd can't run whilst CCcam is running."
msgstr "MGcamd CCcam çalışırken çalışamaz."

#: SoftcamManager.py:237 SoftcamManager.py:291
msgid "Found non-standard softcam, trying to start, this may fail."
msgstr "Standart dışı softcam bulundu, başlatmaya çalışıyor, bu başarısız olabilir."

#: SoftcamManager.py:272
msgid "CCcam can't run whilst MGcamd is running."
msgstr "MGcamd çalışırken CCcam çalışamıyor."

#: SoftcamManager.py:280
msgid ""
"No config files found, please setup Oscam first\n"
"in /etc/tuxbox/config."
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce Oscam'i kurun\n"
"/etc/tuxbox/config içinde."

#: SoftcamManager.py:309
msgid "Softcam starting..."
msgstr "Softcam başlıyor ..."

#: SoftcamManager.py:311
msgid "Please wait while starting\n"
msgstr "Lütfen başlarken bekleyin\n"

#: SoftcamManager.py:426
msgid "Softcam stopping..."
msgstr "Softcam duruyor ..."

#: SoftcamManager.py:428
msgid "Please wait while stopping\n"
msgstr "Lütfen dururken bekleyin\n"

#: SoftcamManager.py:601
msgid "SoftcamCheck"
msgstr "SoftcamCheck"

#: SoftcamManager.py:603
msgid "Checking softcams..."
msgstr "Softcams kontrol ediliyor ..."

#: SwapManager.py:99 ui.py:54
msgid "SWAP manager"
msgstr "SWAP yöneticisi"

#: SwapManager.py:107
msgid "SWAP place:"
msgstr "SWAP yeri:"

#: SwapManager.py:109
msgid "SWAP size:"
msgstr "SWAP boyutu:"

#: SwapManager.py:111
msgid "Status:"
msgstr "Durum:"

#: SwapManager.py:112 SwapManager.py:239
msgid "Inactive"
msgstr "Aktif değil"

#: SwapManager.py:113 SwapManager.py:234
msgid "Active"
msgstr "Aktif"

#: SwapManager.py:115 SwapManager.py:238
msgid "Activate"
msgstr "Etkinleştir"

#: SwapManager.py:116 SwapManager.py:178
msgid "Create"
msgstr "Yarat"

#: SwapManager.py:140 SwapManager.py:234 SwapManager.py:239
msgid "Current status:"
msgstr "Şu anki durum:"

#: SwapManager.py:141
msgid "Wait please while scanning..."
msgstr "Lütfen tararken bekleyin ..."

#: SwapManager.py:233
msgid "Deactivate"
msgstr "Devre dışı bırak"

#: SwapManager.py:241
msgid "Enable SWAP at startup"
msgstr "Başlangıçta SWAP'yi etkinleştir"

#: SwapManager.py:257
msgid "SWAP file not found. You have to create the file before you try to activate it."
msgstr "SWAP dosyası bulunamadı. Etkinleştirmeye çalışmadan önce dosyayı oluşturmanız gerekir."

#: SwapManager.py:258 SwapManager.py:324
msgid "Info"
msgstr "Bilgi"

#: SwapManager.py:290
msgid "Please select device to use as SWAP file location."
msgstr "Lütfen SWAP dosyası konumu olarak kullanılacak cihazı seçin."

#: SwapManager.py:292
msgid "Sorry, no physical devices that supports SWAP attached. Can't create SWAP file on network or fat32 file-systems."
msgstr "Maalesef, SWAP'ı destekleyen hiçbir fiziksel cihaz bağlı değil. Ağda veya fat32 dosya sistemlerinde SWAP dosyası oluşturulamıyor."

#: SwapManager.py:297
msgid "128 Mb"
msgstr "128 Mb"

#: SwapManager.py:297
msgid "16 Mb"
msgstr "16 Mb"

#: SwapManager.py:297
msgid "256 Mb"
msgstr "256 Mb"

#: SwapManager.py:297
msgid "32 Mb"
msgstr "32 Mb"

#: SwapManager.py:297
msgid "64 Mb"
msgstr "64 Mb"

#: SwapManager.py:297
msgid "8 Mb"
msgstr "8 Mb"

#: SwapManager.py:297
msgid "96 Mb"
msgstr "96 Mb"

#: SwapManager.py:298
msgid "Select the SWAP file size:"
msgstr "SWAP dosya boyutunu seçin:"

#: SwapManager.py:303
msgid "Wait please while creating SWAP file..."
msgstr "SWAP dosyası oluşturulurken lütfen bekleyin ..."

#: SwapManager.py:323
msgid "You have to create a SWAP file before trying to activate the autostart."
msgstr "Otomatik başlatmayı etkinleştirmeye çalışmadan önce bir SWAP dosyası oluşturmanız gerekir."

#: plugin.py:81 plugin.py:167 ui.py:42
msgid "Vision"
msgstr "Vizyon"

#: plugin.py:161
msgid "Install extensions."
msgstr "Uzantıları yükle."

#: plugin.py:179
msgid "Opkg"
msgstr "Opkg"

#: plugin.py:180
msgid "Vision Backup manager"
msgstr "Vizyon Yedekleme yöneticisi"

#: plugin.py:181
msgid "Vision Image manager"
msgstr "Vizyon Görüntü yöneticisi"

#: plugin.py:182
msgid "Vision Mount manager"
msgstr "Vision Mount yöneticisi"

#: plugin.py:183
msgid "Vision Script runner"
msgstr "Vision Script koşucusu"

#: plugin.py:184
msgid "Vision SWAP manager"
msgstr "Vizyon SWAP yöneticisi"

#: ui.py:49
msgid "Manage the backups of your settings."
msgstr "Ayarlarınızın yedeklerini yönetin."

#: ui.py:50
msgid "Create and flash complete images of your system."
msgstr "Sisteminizin eksiksiz görüntülerini oluşturun ve flash yapın."

#: ui.py:51
msgid "Install IPK's from your tmp folder."
msgstr "IPK'leri tmp klasörünüzden yükleyin."

#: ui.py:51
msgid "Install local extension"
msgstr "Yerel uzantıyı kur"

#: ui.py:52
msgid "Manage your devices mount points."
msgstr "Cihazlarınızın bağlama noktalarını yönetin."

#: ui.py:53
msgid "Run your shell scripts."
msgstr "Kabuk betiklerinizi çalıştırın."

#: ui.py:54
msgid "Create and Manage your SWAP files."
msgstr "SWAP dosyalarınızı oluşturun ve yönetin."

#: ui.py:56
msgid "Create empty slot."
msgstr "Boş yuva oluştur."

#: ui.py:56
msgid "MultiBoot manager"
msgstr "MultiBoot yöneticisi"

#: ui.py:58
msgid "H9SDcard Manager"
msgstr "H9SDcard Yöneticisi"

#: ui.py:58
msgid "Move Nand root to SD card"
msgstr "Nand ​​kökünü SD karta taşı"
